### ISSUE TITLE
How to call a contract

### ISSUE THREAD

**Issue by zawilliams** [chnejohnson/vue-dapp#11]
Hey @chnejohnson - trying to use this in a Vue app. How do you call a contract method using this?

**Comment by chnejohnson** [comment]
Hello @zawilliams,

you can use `useEthers` to get `signer` which is come from ethers.js, and then you can create a contract by it.

vue-dapp docs: https://vue-dapp-docs.netlify.app/api/use-ethers.html
ethers.js signer docs: https://docs.ethers.io/v5/api/contract/contract/#Contract-connect

```js
const { signer } = useEthers()
const yourContract = new ethers.Contract(contractAddress, abi, signer);
```

This project is under development, so it's not stable. Welcome to contribute. In the future, it will have `useMulticall` for calling contracts in a more efficient way.

**Comment by zawilliams** [comment]
Ah, that makes sense - I was assuming there was another abstraction having to do with contracts. After looking more through the code, that makes sense. Thanks for explaining. Would love to contribute - the simplicity of the package use is really nice.

So I tried using that code and when I'm using `signer` like that, it's giving me this error:

```javascript
Uncaught Error: invalid signer or provider (argument="signerOrProvider", value={"_shallow":false,"__v_isRef":true,"_rawValue":null,"_value":null}, code=INVALID_ARGUMENT, version=contracts/5.4.1)
```

VSCode specifically is giving me:

```javascript
Argument of type 'Ref<{ readonly provider?: { getNetwork: () => Promise<Network>; getBlockNumber: () => Promise<number>; getGasPrice: () => Promise<BigNumber>; getFeeData: () => Promise<...>; ... 24 more ...; readonly _isProvider: boolean; }; ... 16 more ...; _checkProvider: (operation?: string) => void; }>' is not assignable to parameter of type 'Signer | Provider'.
  Type 'Ref<{ readonly provider?: { getNetwork: () => Promise<Network>; getBlockNumber: () => Promise<number>; getGasPrice: () => Promise<BigNumber>; getFeeData: () => Promise<...>; ... 24 more ...; readonly _isProvider: boolean; }; ... 16 more ...; _checkProvider: (operation?: string) => void; }>' is missing the following properties from type 'Provider': getNetwork, getBlockNumber, getGasPrice, getFeeData, and 25 more.Vetur(2345)
const signer: Ref<{
    readonly provider?: {
        getNetwork: () => Promise<ethers.providers.Network>;
        getBlockNumber: () => Promise<number>;
        getGasPrice: () => Promise<ethers.BigNumber>;
        ... 25 more ...;
        readonly _isProvider: boolean;
    };
    ... 16 more ...;
    _checkProvider: (operation?: string) => void;
}>
```

I'm not as familiar with TypeScript, so I'm not sure if this is just TypeScript related.

Any thoughts?

**Comment by zawilliams** [comment]
Ah, duh \*face palm\*. I can't tell you how many times I've forgotten about `.value` with Vue 3 `refs`. Thanks for explaining all of that. Makes sense and got it working.
