### ISSUE TITLE
WalletConnect: Has anyone had this error Failed to load wallet data: Operation timed out?

### ISSUE THREAD

**Issue by Dev-A-Line** [chnejohnson/vue-dapp#126]
Maybe I'm doing something wrong or haven't accounted for some variable, but on Vercel this repository has the same problem.

Failed to load wallet data: Operation timed out

![image](https://user-images.githubusercontent.com/14335460/226215180-c29e50bb-6ee0-4ce7-ac65-0c5c85f5e119.png)

**Comment by re2005** [comment]
Hi @Dev-A-Line can you provide the repo ? Or more details about the issue?

**Comment by Dev-A-Line** [comment]
Hi @re2005  can be used to demonstrate the problem - [vuedapp.vercel.app/](https://vuedapp.vercel.app/) as the same problem occurs locally. Pressing Connect > WalletConnect [ws:*** || qr]> redirects to TrastWallet and asks to approve and then this error appears: Failed to load wallet data: Operation timed out.

**Comment by re2005** [comment]
Yes, facing the same issue here.

It seems that the `RPC` server used by the demo is not working properly.

Locally you can try yo use one of the public `RPC` servers, check on https://chainlist.org/ for the desired network you are trying to connect.

<img width="630" alt="Screenshot 2023-03-20 at 11 17 10" src="https://user-images.githubusercontent.com/2920357/226310945-982d637d-7711-4307-bfd2-f101ef9353f7.png">

**Comment by Dev-A-Line** [comment]
Got it, thanks, I'll try it now. Sorry for the stupid question 🙈

**Comment by re2005** [comment]
No problem, (there are no stupid questions)
I've updated the demo, you can try again connect to (Mainnet or Goerli) using WalletConnect:

https://vue-dapp-git-issue-117-chnejohnson.vercel.app/

Cheers

**Comment by Dev-A-Line** [comment]
![image](https://user-images.githubusercontent.com/14335460/226315800-1d390eb3-1f5e-4d19-8ef1-43eff3307011.png)
Maybe infuraId is causing a problem

**Comment by re2005** [comment]
I placed the wrong URL here.

This is correct:
https://vue-dapp-git-fork-re2005-feature-update-demo-chnejohnson.vercel.app/

**Comment by Dev-A-Line** [comment]
@re2005  Got it, thank you very much again
