### ISSUE TITLE
Logo for vue-dapp

### ISSUE THREAD

**Issue by scco** [chnejohnson/vue-dapp#16]
hey hey chnejohnson, you reached out some days ago on dgrants so i checked out your library. nice job.
checkout : https://schumanncombo.com/web3modal/

if you would like to enable custom dom-structures like my simple html example 
or wana use my icons - you can find all the icons here.  https://fusion.li  

theres also a primitive vue library what i do not maintain as i lack in that skill :) 
https://www.npmjs.com/package/@fusion-icons/vue

all the best, richard from berlin

**Comment by chnejohnson** [comment]
Refer to #24
