### ISSUE TITLE
Connect multiple accounts, when switching accounts, it will execute onchanged many times

### ISSUE THREAD

**Issue by beifang721** [chnejohnson/vue-dapp#22]
![image](https://user-images.githubusercontent.com/19699178/142449712-277aaa8f-3e72-405d-a011-1c7dbb5b2fff.png)

**Comment by beifang721** [comment]
@coxlr @chnejohnson

**Comment by chnejohnson** [comment]
Hey beifang721, what's your vue-dapp version? What's the code you write? Please tell me more details so that I could reproduce the problem.

**Comment by beifang721** [comment]
"vue-dapp": "^0.4.2",
```
onChanged((data) => {
  try {
    if (chainId.value === 1) {
      if (data.address) {
        store.state.user.isLoggedIn = true;
        store.state.user.wallet = data.address;
        login()
      }
    } else {
      message.error("sorry,Only supports Ethereum!!!");
    }
  } catch (error) {
    console.log(error);
  }
});
```
Another question, why onChanged is triggered when I switch accounts on other websites?   thanks!!!

**Comment by beifang721** [comment]
@chnejohnson thanks

**Comment by chnejohnson** [comment]
> Another question, why onChanged is triggered when I switch accounts on other websites?
Yes, it makes sense. `onChanged` would follow up your metamask extension on the browser.

As for executing `onChanged` many times, I need more information. You should notice that you only add one `onChanged` listener. It's possible that you have a vue component added the `onChanged`, but the component is created multiple times. So you would add multiple `onChanged` listener in your app.

**Comment by beifang721** [comment]
@chnejohnson    If onchanged is triggered multiple times, the changed component has been quoted multiple times, which can be solved by anti-shake.

onChanged would follow up your metamask extension on the browser. How should I judge whether the current website triggered `onchanged`? Because I signed `onchanged`

**Comment by beifang721** [comment]
a When the website switches the wallet, metamask will receive the signature of another website   @chnejohnson

**Comment by chnejohnson** [comment]
> a When the website switches the wallet, metamask will receive the signature of another website @chnejohnson

Okay, I've got your point. The problem is that `onChanged` will be triggered no matter browser's tab is active or not. So I think we should prevent from triggering `onChanged` when the browser's tab is inactive, right?

**Comment by chnejohnson** [comment]
Try `v0.5.1`, if you still have the problem, please post a new issue again.
