### ISSUE TITLE
Gitcoin grants

### ISSUE THREAD

**Issue by ramuta** [chnejohnson/vue-dapp#24]
Hi @chnejohnson! I love this project ❤️  Us Vue devs also need a web3 library/starter kit like this (everything else is made for React).

That said, I'm wondering if you intend to apply for a Gitcoin grant in the upcoming round 12?

If you do, please let me know, I'll be happy to donate to it (and you'll also get matched by Gitcoin sponsors).

P.S.: The hackathon for the Gitcoin Grants Round 12 starts on 1 Dec, not sure if you need to apply in order to post a grant, but here's the link anyway: https://gitcoin.co/hackathon/gr12/

**Comment by chnejohnson** [comment]
Hey @ramuta, I'm so happy to hear that!
I would try to apply for a Gitcoin grant recently, thanks for your support. :)

**Comment by chnejohnson** [comment]
By the way, though having a project logo is not necessary to apply for a Gitcoin grant, I'm still looking forward to having a logo for this project, see issue #16.

**Comment by ramuta** [comment]
Yeah, I'm not a designer, but I managed to put together these 4 images:

![](https://i.imgur.com/mqMkBXt.png)

![](https://i.imgur.com/GVDBWjX.png)

![](https://i.imgur.com/cKUiGGm.png)

![](https://i.imgur.com/q8Xi7BA.png)

Could one of these work until you get something more professional done? 🙂

**Comment by chnejohnson** [comment]
@ramuta Cool, the second one looks good to me. It seems that this project has an initial logo. Thanks!

**Comment by chnejohnson** [comment]
The grant has eventually been approved! Thanks so much for @ramuta's logo. It looks really clear and beautiful. 🖖
