### ISSUE TITLE
Metamask on mobile devices

### ISSUE THREAD

**Issue by coxlr** [chnejohnson/vue-dapp#26]
I've noticed on my dapps using this package that on mobile devices the MetaMask option is greyed out as it is not available. This is the currently the expected behavior. However they can still use MetaMask via the WalletConnect option, but currently this is unclear to the end user.

What are your thoughts on the best way to handle this? I am thinking in the greyed out MetaMask option, update the text on mobile devices to say something like "Use WalletConnect on Mobile Device" something like the below

![Screen Shot 2021-11-30 at 2 57 29 PM](https://user-images.githubusercontent.com/8451762/144141559-714b67f9-aab8-483e-afbe-ec376682a990.png)

I'm happy to make a pull request for this, but wanted to see your thoughts on it first.

**Comment by chnejohnson** [comment]
Hi @coxlr, I prefer to remove MetaMask option on the mobile device. How does that sound?

**Comment by chnejohnson** [comment]
BTW, I find a bug about MetaMask mobile app that cannot connect to VueDapp site with walletconnect. What's even worse is that the walletconnect session would not be disconnected so the website will be stuck though reloading the page can't recovery.

**Comment by coxlr** [comment]
I think it's important to still have a MetaMask option on mobile devices as this is the most widely used wallet currently. How about simply using a deep link to the MetaMask wallet browser if on a mobile, so if they are on a mobile device and click the MetaMask option it deep links to the MetaMask wallet browser if installed, and if it is not installed it opens up the app store.

A MetaMask deep link would use the require the app url to be set, and the deep link looks like below: https://metamask.app.link/dapp/websiteurl.com

See: https://metamask.github.io/metamask-deeplinks

**Comment by chnejohnson** [comment]
Cool, it's good to me. 👍
