### ISSUE TITLE
Walletconnect is not suitable for integration by vite ES modules environment

### ISSUE THREAD

**Issue by chnejohnson** [chnejohnson/vue-dapp#3]
## Problem
Vite is ES module only. There are many codes in Walletconnect that rely on node builtins or others.

## Reproduce
checkout branch issue#3

Run `yarn dev` for demo

<img width="648" alt="截圖 2021-08-23 下午1 01 49" src="https://user-images.githubusercontent.com/31992185/130392917-19043e0d-de88-45bb-a1a0-ad708bbb9d64.png">

### index.ts:19
I don't know where this file comes from.
@walletconnect/socket-transport/src/index.ts
```
Could not load content for http://localhost:3000/@fs/Users/***/Desktop/vue-dapp/node_modules/@walletconnect/socket-transport/src/index.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
```
### Code
The problem is import @walletconnect/web3-provider. If remove this line, it works.
```
import WalletConnectProvider from '@walletconnect/web3-provider'

export function useWalletconnect() {
  async function getProvider() {
    //  Create WalletConnect Provider
    const provider = new WalletConnectProvider({
      infuraId: '27e484dcd9e3efcfd25a83a78777cdf1',
    })

    //  Enable session (triggers QR Code modal)
    await provider.enable()

    return provider
  }

```

**Comment by chnejohnson** [comment]
vite.config.js add below can solve the problem,

```
// https://github.com/vitejs/vite/issues/2782#issuecomment-810226342
  define: {
    global: JSON.stringify({}),
  },
```

but there is new problem...

- https://github.com/vitejs/vite/issues/2782

<img width="649" alt="截圖 2021-08-23 下午2 03 25" src="https://user-images.githubusercontent.com/31992185/130398162-e47fa043-469d-4d6e-b968-ef0c33ee99e9.png">

some resource:
- https://github.com/vitejs/vite/discussions/3126
- https://github.com/vitejs/vite/issues/792
- https://www.npmjs.com/package/buffer (not works)

**Comment by chnejohnson** [comment]
### How about building the library with vue-cli?
- https://stackoverflow.com/questions/68935115/can-vue-cli-build-a-library-for-vue-3

**Comment by chnejohnson** [comment]
# Viable Solution

`<script src="https://cdn.jsdelivr.net/npm/@walletconnect/web3-provider@1.6.5/dist/umd/index.min.js"></script>`

refer: e791bec808a05fa0992eda934e5641fb095f22b6

**Comment by Fy-** [comment]
Vue3 (head of your index.html)
```
    <script type="module">
      import { Buffer } from "buffer";
      import EventEmitter from "events";

      window.Buffer = Buffer;
      window.EventEmitter = EventEmitter;
    </script>
```

( "process.env": process.env, in define in vite.config.js)

**Comment by pauloreis7** [comment]
> <script type="module">
>       import { Buffer } from "buffer";
>       import EventEmitter from "events";
> 
>       window.Buffer = Buffer;
>       window.EventEmitter = EventEmitter;
>     </script>

Thanks, it solved the problem! With react and vitejs it was giving this bug, but with this everything is fixed
