### ISSUE TITLE
metamask is not connected

### ISSUE THREAD

**Issue by AnvinMao** [chnejohnson/vue-dapp#30]
If I install both metamask and coinbase, connect to metamask will prompt "metamask is not connected"

![Screenshot 2021-12-24 234907](https://user-images.githubusercontent.com/5878336/147363245-d58e4b13-e61d-4866-9013-2a3b888805fa.png)

**Comment by chnejohnson** [comment]
Ooh, I haven't used coinbase browser extension before. Let me find out the solution.

**Comment by tempe-techie** [comment]
It may be because the browser considers Coinbase wallet as the default wallet, not MetaMask.
