### ISSUE TITLE
Is it possible to inject custom RPC URL?

### ISSUE THREAD

**Issue by tempe-techie** [chnejohnson/vue-dapp#31]
Hey @chnejohnson 

I see options to connect to blockchain are MetaMask, Coinbase, and Infura ID.

But what about connecting with a specific RPC URL?

Let's say I want users to see blockchain data from a smart contract no matter if they are connected with their wallet, or not. For example, for the Polygon blockchain I'd use `https://polygon-rpc.com/`. This way I'd get data from Polygon even if a user is not connected with MetaMask yet.

Can I insert this RPC URL somewhere in vue-dapp? Or would I need to inject it into ethers.js?

**Comment by chnejohnson** [comment]
Hi @tempe-techie. Ya, I think you can inject it into ethers.js
