### ISSUE TITLE
Demand advice

### ISSUE THREAD

**Issue by EndureBlaze** [chnejohnson/vue-dapp#37]
Can you add a WalletConnect scan method?

**Comment by chnejohnson** [comment]
Not sure what you want. Can you be a little more specific?

**Comment by EndureBlaze** [comment]
> Not sure what you want. Can you be a little more specific?

Like this

https://community.trustwallet.com/t/how-to-use-walletconnect-with-trust-wallet/36247

**Comment by EndureBlaze** [comment]
Sorry, I just seem to have seen what I need
