### ISSUE TITLE
Custom RPC URL for WalletConnect

### ISSUE THREAD

**Issue by tempe-techie** [chnejohnson/vue-dapp#39]
Hi!

Currently WalletConnect only works with Infura ID. The problem with Infura is that it does **not** support many chains, like for example Gnosis Chain (former xDai Chain).

So I was wondering if I can somehow use WalletConnect without Infura ID (with a custom RPC URL)?

In `src/wallets/walletconnect.ts` there's the connect function which takes infuraID as an input:

```typescript
static async connect(
    infuraId: string,
    options?: IWalletConnectProviderOptions,
  ) {
    const provider = new WalletConnectProviderDerived!({
      infuraId,
      ...options,
    })
```

The `...options` part can include many things, among them also `rpcUrl`. So how can I inject the RPC URL in this case?

Maybe in main.ts like this:

```typescript
app.use(VueDapp, {
  infuraId: '',
  {
    rpcUrl: 'https://rpc.gnosischain.com'
  }
})
```

Also I'd need the RPC URL to change when the network is changed (for example from Gnosis to Polygon)...

Any advice on how to make this work? 🙂

**Comment by chnejohnson** [comment]
Ok, I think the plugin API can be like: 

```ts
app.use(VueDapp, {
  infuraId: '',
  walletConnectOptions: {
    rpcUrl: 'https://rpc.gnosischain.com'
  }
})
```

And the rpcUrl should inject into the `src/components/Board.vue`, and then you should also fix `src/composables/useWallet` connect function for accepting new parameter like "walletConnectOptions". So it can pass it into `src/wallets/walletconnect.ts`.

```ts
function useWallet(options: UseWalletOptions = { library: 'ethers' }) {
  const { activate, deactivate } = useEthers()

  ...

  async function connect(
    _walletName: WalletName,
    infuraAPI?: string,
    appName?: string,
    walletConnectOptions?: any                                                       // add this line
  ) {
    let _provider: WalletProvider | null = null

    error.value = ''

    try {
      status.value = 'connecting'
      switch (_walletName) {
        case 'metamask':
          _provider = (await Metamask.connect()) as MetaMaskProvider
          if (!_provider.isConnected)
            throw new Error('metamask is not connected')
          break
        case 'walletconnect':
          if (!infuraAPI)
            throw new Error(
              'You should provide infuraAPI for connecting WalletConnect',
            )
          _provider = (await Walletconnect.connect(
            infuraAPI,
            walletConnectOptions,                                                       // and this line
          )) as WalletConnectProvider
          if (!_provider.connected)
            throw new Error('walletconnect is not connected')
          break
        case 'walletlink':
      ...
```

But I'm not sure that the plugin option can be reactive for changing rpc url when the network is changed.

```ts
export type PluginOptions = {
  infuraId?: string
  appName?: string
  appUrl?: string
  walletConnectOptions?: any              // add this line
}
```

**Comment by tempe-techie** [comment]
Hm, maybe when network is changed, the wallet would first automatically get disconnected and then the connect() function would be called again with a different RPC URL?

If that wouldn't work, then the frontend should not allow network switching if user uses WalletConnect, unless the user first disconnects manually...
