### ISSUE TITLE
Doesn't work quick start

### ISSUE THREAD

**Issue by Alex-Lorem** [chnejohnson/vue-dapp#46]
Hello everybody! I am really want to use this cool plugin, but I have problems with starting. I have created a new Vue 3 default project, and did everything what was in "getting started". But my webpack doesnt want to compile, it shows me 13 errors and each about this:
_BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it._ 
![image](https://user-images.githubusercontent.com/66880682/170517351-bdbd8e44-6b14-4547-9743-ec4f2c8981be.png)

     Was anyone interacted with that? I was googling about it, and the solution was to add target: 'node' in webpack.config.js. Now I can compile, but there are some errors in browser console instead.

![image](https://user-images.githubusercontent.com/66880682/170516945-10d154b8-c2c2-43d4-8f0e-1ec512e14cf7.png)
     **This problem about migrating webpack 4 to 5? If you have some information or expirience tell me please.
Thanks.**

**Comment by chnejohnson** [comment]
Hi @Alex-Lorem, maybe you can try to install `node-polyfill-webpack-plugin": "^1.1.4`, and have `vue.config.js` as follows:
```js
const { defineConfig } = require('@vue/cli-service')
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin')

console.log('Environment:', process.env.NODE_ENV)

module.exports = defineConfig({
  transpileDependencies: true,
  configureWebpack: {
    plugins: [new NodePolyfillPlugin()],
  },
  publicPath: process.env.NODE_ENV === 'production' ? '/macier/' : '/',
})
```

**Comment by Alex-Lorem** [comment]
Thank you a lot!
