### ISSUE TITLE
Add Gnosis Safe

### ISSUE THREAD

**Issue by chnejohnson** [chnejohnson/vue-dapp#52]
sdk: https://docs.gnosis-safe.io/build/sdks/safe-apps/build

**Comment by chnejohnson** [comment]
@re2005 No, sorry. My hands are full recently. Do you want to make it work?

**Comment by re2005** [comment]
Already trying to fix this.

https://github.com/safe-global/safe-apps-sdk/issues/337

**Comment by fran6brg** [comment]
Hi @re2005 
Any update on the integration of gnosis ? If not I might give it a try soon
Thanks

**Comment by re2005** [comment]
@fran6brg in order to use `Gnosis Safe` you should do something like this:

You will need to install `@gnosis.pm/safe-apps-wagmi`


```ts
import { MetaMaskConnector, WalletConnectConnector } from 'vue-dapp';
import { SafeConnector } from '@gnosis.pm/safe-apps-wagmi';

const isServer = typeof window === 'undefined';
const isIframe = !isServer && window?.parent !== window;

const connectors: any = [
    new MetaMaskConnector({
        appUrl: window.location.href,
    }),
    new WalletConnectConnector({
        qrcode: true,
        rpc: {},
    }),
];

if (isIframe) {
    connectors.push(new SafeConnector({}));
}

export const isGnosisSafeApp = isIframe;

export default connectors;

```

So basically within your connect you can check if your dapp is running inside GnosisSafe and than just use 

```ts
new SafeConnector({})
```

Give it a try ;)

**Comment by fran6brg** [comment]
Just tested your suggestion of code, for me it works perfectly 🙏
I only had some minor typescript issues but surely because I modified the vue-dapp package a bit

**Comment by re2005** [comment]
@fran6brg please feel free to suggest improvements for this repo as well.

Cheers.

**Comment by chnejohnson** [comment]
> You will need to install `@gnosis.pm/safe-apps-wagmi`
> 
> ```ts
> import { MetaMaskConnector, WalletConnectConnector } from 'vue-dapp';
> import { SafeConnector } from '@gnosis.pm/safe-apps-wagmi';
> 
> const isServer = typeof window === 'undefined';
> const isIframe = !isServer && window?.parent !== window;
> 
> const connectors: any = [
>     new MetaMaskConnector({
>         appUrl: window.location.href,
>     }),
>     new WalletConnectConnector({
>         qrcode: true,
>         rpc: {},
>     }),
> ];
> 
> if (isIframe) {
>     connectors.push(new SafeConnector({}));
> }
> 
> export const isGnosisSafeApp = isIframe;
> 
> export default connectors;
> ```
> 
> So basically within your connect you can check if your dapp is running inside GnosisSafe and than just use
> 
> ```ts
> new SafeConnector({})
> ```
> 
> Give it a try ;)

Seems that this solution can be written down on the document and then it's better to close this issue
