### ISSUE TITLE
Is it possible to use my own "board" UI, or even none at all?

### ISSUE THREAD

**Issue by str11ngfello** [chnejohnson/vue-dapp#60]
I like the board UI a lot and have been using it from the beginning. (useBoard) Now that our UI has grown in complexity we need to have full control over the UI. 

For example, I'm in a dialog or two already and the useBoard call presents behind my dialogs. 

Question: is there a way to call the same function that selecting "metamask" or "coinbase" would call on the board, thereby letting us programmatically specify the connector to use? (including just auto choosing a wallet for the user without giving them a choice)

Thanks for a great library!

**Comment by str11ngfello** [comment]
Here's an example with a visual. Figured you'll like to see a project really using your library! The user is asked to choose a warrior by connecting a wallet. The board is actually displayed behind this quasar (vue3 lib) dialog (the problem). I'm unsure how to make your UI and quasar dialog system aware of each other and would prefer to just have full control over the UI from here on out.

![image](https://user-images.githubusercontent.com/877000/175824101-8f0af817-e58c-4d5b-9088-d23db4abf96f.png)

**Comment by chnejohnson** [comment]
Hey, I think you can write your own custom `Board.vue` component like this:
https://github.com/chnejohnson/vue-dapp/blob/main/src/components/Board.vue

**Comment by re2005** [comment]
All you need is use the method `connectWith(connector)`

```ts
const { connectWith } = useWallet()

cost connector = new MetaMaskConnector({
    appUrl: window.location.href,
}

connectWith(connector)
```
