### ISSUE TITLE
When extended the new connector doesn't show up inside the modal

### ISSUE THREAD

**Issue by re2005** [chnejohnson/vue-dapp#66]
Here you list the connectors:

`https://github.com/chnejohnson/vue-dapp/blob/main/src/components/Board.vue#L82`

It's not printing the name/icon or anything from the new Connector.

<img width="375" alt="Screenshot 2022-07-05 at 15 35 15" src="https://user-images.githubusercontent.com/2920357/177340472-1cd9153b-f323-457c-8980-4b5c1fb41a3f.png">

**Comment by chnejohnson** [comment]
The icon and name are printed based on the following code:
https://github.com/chnejohnson/vue-dapp/blob/4df55dbef7623db411992c8d2c31846242c9233e/src/components/Board.vue#L57-L79
