### ISSUE TITLE
Vue-dapp please consider having a new collaborator  🚀

### ISSUE THREAD

**Issue by re2005** [chnejohnson/vue-dapp#73]
Hi @chnejohnson, thanks for creating Vue-dapp.

Since I found your project, I'm spending quite some time using, testing and improving the user experience and of course fixing  small bugs.

I enjoy contributing and helping people in the js / web3 community!

Cheers

**Comment by chnejohnson** [comment]
Hey, @re2005  thanks, I have sent you an invite.
