### ISSUE TITLE
vuecli4

### ISSUE THREAD

**Issue by vivilau** [chnejohnson/vue-dapp#75]
how can use vue-dapp with vuecli4?
thx

**Comment by re2005** [comment]
Hi @vivilau this is not really an issue sounds more like a question.

You just do `npm install ethers vue-dapp`

@chnejohnson perhaps we open the `discussion` tab so people can ask questions like this.

**Comment by chnejohnson** [comment]
@vivilau Hey, if you have some errors when integrating vue-dapp with vuecli4, please open a new issue and post the error message. Good luck!
@re2005 Maybe we can just close this issue
