### ISSUE TITLE
How to add new kind of wallet, such as TokenPocket, tks

### ISSUE THREAD

**Issue by YCL686** [chnejohnson/vue-dapp#82]

**Comment by chnejohnson** [comment]
Hello @YCL686, my advice is to take a look at [how metamask wallet implements the connector](https://github.com/chnejohnson/vue-dapp/blob/main/src/wallets/metaMask.ts), and maybe you can find out a way to integrate with TokenPocket.

**Comment by re2005** [comment]
@chnejohnson maybe we can move this to the `discussions` and clean up the issues.

**Comment by chnejohnson** [comment]
> @chnejohnson maybe we can move this to the `discussions` and clean up the issues. 

Agree
