### ISSUE TITLE
Issue with flag autoConnect: true when using inside Gnosis-safe.io

### ISSUE THREAD

**Issue by re2005** [chnejohnson/vue-dapp#89]
The `autoconnect` feature works nicely, but once you running your all inside GnosisSafe it will give you some errors:

https://gnosis-safe.io/

I'm not sure is because the way I'm extending the connectors, here is the sample of code I'm using:

```
import { MetaMaskConnector, WalletConnectConnector } from 'vue-dapp';
import { supportedChains } from '@/blockchain/chains/supportedChains';
import { SafeConnector } from '@gnosis.pm/safe-apps-wagmi';

const isServer = typeof window === 'undefined';
const isIframe = !isServer && window?.parent !== window;

const connectors: any = [
    new MetaMaskConnector({
        appUrl: window.location.href,
    }),
    new WalletConnectConnector({
        qrcode: true,
        rpc: Object.values(supportedChains).reduce((acc, cur) => ({ ...acc, [cur.chainId]: cur.rpcUrls[0] }), {}),
    }),
];

if (isIframe) {
    connectors.push(new SafeConnector({}));
}

export const isGnosisSafeApp = isIframe;
export default connectors;
```

Perhaps the autoConnect should search if `Safe` connector is available and connect to it, instead of `Metamask`
And maybe we should start giving support for `Gnosis Safe` app as well. Providing the connector from `'@gnosis.pm/safe-apps-wagmi`

**Comment by chnejohnson** [comment]
Will do some research and implement this.
