### ISSUE TITLE
页面刷新,provider为null，同时也无法断开链接

### ISSUE THREAD

**Issue by atlantischen** [chnejohnson/vue-dapp#95]

**Comment by chnejohnson** [comment]
@atlantischen 你好，麻煩提供重現的方式或完整的錯誤訊息，以及使用哪款錢包發生的狀況？

**Comment by atlantischen** [comment]
> @atlantischen你好，事务提供了返回的方式或完整的错误消息，以及使用哪款钱包发生的情况？

![image](https://user-images.githubusercontent.com/52541580/199190061-71817591-8ca5-4916-a779-b2dd32699f62.png)
页面刷新式数据消失，链接状态也没有了，页面刷新如何保存登录状态呢,让监听事件继续监听

**Comment by chnejohnson** [comment]
刷新頁面一定會斷開連線，你可以使用 vue-router 去做保持連線的頁面切換，或者使用 v0.6.0 的版本，提供載入後自動連線的功能
```js
app.use(VueDapp, {
 autoConnect: true, // Automatically connect MetaMask wallet when the page is loaded
  networks: {
    80001: {
      chainId: ethers.utils.hexValue(80001),
      blockExplorerUrls: ['https://mumbai.polygonscan.com/'],
      chainName: 'Mumbai',
      rpcUrls: ['https://rpc-mumbai.maticvigil.com/'],
      nativeCurrency: {
        name: 'Mumbai',
        decimals: 18,
        symbol: 'MATIC',
      },
    },
    42161: {
      ...
    },
  },
});
```

**Comment by atlantischen** [comment]
那如果需要增加其他钱包链接呢，如何增加

**Comment by atlantischen** [comment]
还有这个autoConnect只能支持metaMask吗？如果需要支持其他钱包呢，怎么修改

**Comment by chnejohnson** [comment]
> 那如果需要增加其他钱包链接呢，如何增加

See Discussion #85 

> 还有这个autoConnect只能支持metaMask吗？如果需要支持其他钱包呢，怎么修改

目前正在開發支援 Gnosis Safe，See PR #94

**Comment by atlantischen** [comment]
还有项目打包以后，只能支持到metamaks,其他钱包都会报错哦

**Comment by atlantischen** [comment]
![image](https://user-images.githubusercontent.com/52541580/199658878-051cb67d-728f-4fd4-8e1a-83db1aac8883.png)

**Comment by chnejohnson** [comment]
> 还有项目打包以后，只能支持到metamaks,其他钱包都会报错哦

我測試 WalletConnect 和 Coinbase 都沒有問題，請問你能說明一下測試的流程和狀況嗎？
